name  := _bw_profile
type  := shared_library
bindir = $(BW_SERVER_TOOLS_BIN_DIR)

include $(BW_COMPONENT_HEADER)

cxxSource =						\
	bw_profile					\


dependsOn = cstdmf

usePython := 1
# BIGWORLD(c++23 migration): was useSystemPython := 1 -- see
# message_logger/Makefile.message_reader for rationale; build against the
# vendored 3.13 headers instead of an arbitrary system python.
useSystemPython := 0

include $(BW_COMPONENT_FOOTER)

# vi: filetype=make
# Makefile.message_reader - bw_profile
